image: node

pipelines:
  branches:
    main:
      - step:
          name: "Debug environment variable"
          script:
            - echo "Checking API Key"
            - echo $OPENAI_API_KEY
      - step:
          name: Build and Deploy to Production
          script:
            - npm install
            - npm i react-router-dom
            - npm run build
            - echo "REACT_APP_OPENAI_API_KEY=$OPENAI_TOKEN" >> .env
            - pipe: atlassian/firebase-deploy:0.2.4
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: $FIREBASE_PROJECT