image: node

pipelines:
  default:
    - step:
        name: Start
        script:
          - npm install 
<<<<<<< HEAD
          - npm run build
=======
          - npm run start
>>>>>>> origin/MIRANDA-27-project-directory-structure-s

    - step:
        name: Deploy to Firebase
        deployment: production
        script:
          - pipe: atlassian/firebase-deploy:0.2.4
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $FIREBASE_PROJECT